// components/ExportModal.jsx — Export pipeline to Python / SQL code
import { useState } from 'react';
import { Icon } from '@iconify/react';
import { useStore } from '../store';
import { topoSort } from '../utils/executor';

export function ExportModal({ onClose }) {
  const [activeTab, setActiveTab] = useState('python');
  const [copied, setCopied] = useState(false);
  const nodes = useStore(s => s.nodes);
  const edges = useStore(s => s.edges);

  const pythonCode = generatePython(nodes, edges);
  const sqlCode = generateSQL(nodes, edges);
  const code = activeTab === 'python' ? pythonCode : sqlCode;

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 animate-fadein" onClick={onClose}>
      <div className="w-full max-w-2xl rounded border border-[#283242] bg-[#1B2028] shadow-2xl overflow-hidden" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="flex items-center justify-between border-b border-[#283242] bg-[#14171C] px-4 py-3">
          <div className="flex items-center gap-2">
            <Icon icon="ci:code" className="text-lg text-[#E8823C]" />
            <div>
              <h3 className="font-sans text-sm font-bold text-[#EDEFF2]">[CODE GENERATOR]</h3>
              <p className="font-mono text-[10px] text-[#7C8698]">Auto-generated Python/SQL script for current pipeline topology</p>
            </div>
          </div>
          <button onClick={onClose} className="flex h-6 w-6 items-center justify-center rounded border border-[#283242] text-[#7C8698] hover:text-[#EDEFF2] hover:bg-[#232B36]">
            <Icon icon="ci:close-md" className="h-4 w-4" />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-[#283242] bg-[#14171C] px-4 pt-2 gap-4">
          <button
            onClick={() => setActiveTab('python')}
            className={`pb-2 font-mono text-xs font-semibold border-b-2 transition-colors flex items-center gap-1.5 ${activeTab === 'python' ? 'border-[#E8823C] text-[#E8823C]' : 'border-transparent text-[#7C8698] hover:text-[#EDEFF2]'}`}
          >
            <Icon icon="ci:file-code" className="h-3.5 w-3.5" />
            <span>[PYTHON (PANDAS)]</span>
          </button>
          <button
            onClick={() => setActiveTab('sql')}
            className={`pb-2 font-mono text-xs font-semibold border-b-2 transition-colors flex items-center gap-1.5 ${activeTab === 'sql' ? 'border-[#E8823C] text-[#E8823C]' : 'border-transparent text-[#7C8698] hover:text-[#EDEFF2]'}`}
          >
            <Icon icon="ci:data" className="h-3.5 w-3.5" />
            <span>[SQL (ANSI)]</span>
          </button>
        </div>

        {/* Code area */}
        <div className="p-4 relative">
          <button
            onClick={handleCopy}
            className="btn-copper absolute top-6 right-6 font-mono text-xs py-1 px-3"
          >
            <Icon icon={copied ? 'ci:check' : 'ci:copy'} className="h-3.5 w-3.5 text-[#14171C]" />
            <span>{copied ? 'COPIED!' : 'COPY CODE'}</span>
          </button>
          <pre className="p-4 rounded border border-[#283242] bg-[#14171C] text-[#EDEFF2] font-mono text-xs overflow-x-auto max-h-[380px] leading-relaxed">
            <code>{code}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}

function generatePython(nodes, edges) {
  if (!nodes.length) return '# Pipeline is empty';
  let order = [];
  try { order = topoSort(nodes, edges); } catch { return '# Error: Pipeline has a cycle'; }

  const lines = [
    'import pandas as pd',
    'import numpy as np',
    '',
    '# Generated by Qyntro Visual Data Pipeline Studio',
    '',
  ];

  const nodeMap = new Map(nodes.map(n => [n.id, n]));
  let varCounter = 1;
  const dfVarMap = new Map();

  for (const id of order) {
    const node = nodeMap.get(id);
    const varName = `df_${varCounter++}`;
    dfVarMap.set(id, varName);

    const inEdges = edges.filter(e => e.target === id);
    const parentVar = inEdges[0] ? dfVarMap.get(inEdges[0].source) : null;
    const data = node.data || {};

    lines.push(`# Node: ${node.data?.label || node.type} (${id})`);

    switch (node.type) {
      case 'load':
        lines.push(`${varName} = pd.read_csv('data.csv')`);
        break;
      case 'dropNulls':
        if (data.cols) {
          const colsStr = data.cols.split(',').map(c => `'${c.trim()}'`).join(', ');
          lines.push(`${varName} = ${parentVar}.dropna(subset=[${colsStr}])`);
        } else {
          lines.push(`${varName} = ${parentVar}.dropna()`);
        }
        break;
      case 'fillNulls':
        lines.push(`${varName} = ${parentVar}.fillna('${data.val || 0}')`);
        break;
      case 'dedupe':
        lines.push(`${varName} = ${parentVar}.drop_duplicates()`);
        break;
      case 'trimStrings':
        lines.push(`${varName} = ${parentVar}.apply(lambda x: x.str.trim() if x.dtype == "object" else x)`);
        break;
      case 'filterRows':
        if (data.col && data.val) {
          lines.push(`${varName} = ${parentVar}[${parentVar}['${data.col}'] ${data.op || '=='} ${isNaN(data.val) ? `'${data.val}'` : data.val}]`);
        } else {
          lines.push(`${varName} = ${parentVar}.copy()`);
        }
        break;
      case 'selectCols':
        if (data.cols) {
          const cStr = data.cols.split(',').map(c => `'${c.trim()}'`).join(', ');
          lines.push(`${varName} = ${parentVar}[[${cStr}]]`);
        } else {
          lines.push(`${varName} = ${parentVar}.copy()`);
        }
        break;
      case 'sort':
        if (data.col) {
          lines.push(`${varName} = ${parentVar}.sort_values(by='${data.col}', ascending=${data.dir !== 'desc'})`);
        } else {
          lines.push(`${varName} = ${parentVar}.copy()`);
        }
        break;
      case 'aggregate':
        if (data.groupBy) {
          lines.push(`${varName} = ${parentVar}.groupby('${data.groupBy}').agg({'${data.aggCol || 'id'}': '${data.aggFn || 'sum'}'}).reset_index()`);
        } else {
          lines.push(`${varName} = ${parentVar}.copy()`);
        }
        break;
      case 'export':
        lines.push(`${parentVar}.to_csv('${data.filename || 'output'}.csv', index=False)`);
        lines.push(`${varName} = ${parentVar}`);
        break;
      default:
        lines.push(`${varName} = ${parentVar ? parentVar + '.copy()' : 'pd.DataFrame()'}`);
        break;
    }
    lines.push('');
  }

  lines.push('print("Pipeline executed successfully!")');
  return lines.join('\n');
}

function generateSQL(nodes, edges) {
  if (!nodes.length) return '-- Pipeline is empty';
  let order = [];
  try { order = topoSort(nodes, edges); } catch { return '-- Error: Pipeline has a cycle'; }

  const lines = ['-- Generated SQL query by Qyntro', ''];
  const nodeMap = new Map(nodes.map(n => [n.id, n]));
  const cteMap = new Map();
  let cteCounter = 1;

  for (let i = 0; i < order.length; i++) {
    const id = order[i];
    const node = nodeMap.get(id);
    const cteName = `step_${cteCounter++}`;
    cteMap.set(id, cteName);

    const inEdges = edges.filter(e => e.target === id);
    const parentCte = inEdges[0] ? cteMap.get(inEdges[0].source) : null;
    const data = node.data || {};

    const isFirst = i === 0;
    const isLast = i === order.length - 1;

    let query = '';
    switch (node.type) {
      case 'load':
        query = `SELECT * FROM source_table`;
        break;
      case 'filterRows':
        query = `SELECT * FROM ${parentCte} WHERE ${data.col || 'id'} ${data.op || '='} '${data.val || ''}'`;
        break;
      case 'sort':
        query = `SELECT * FROM ${parentCte} ORDER BY ${data.col || '1'} ${data.dir || 'ASC'}`;
        break;
      case 'aggregate':
        query = `SELECT ${data.groupBy || 'category'}, ${data.aggFn || 'SUM'}(${data.aggCol || 'value'}) FROM ${parentCte} GROUP BY ${data.groupBy || 'category'}`;
        break;
      default:
        query = `SELECT * FROM ${parentCte || 'source_table'}`;
        break;
    }

    if (isFirst) {
      lines.push(`WITH ${cteName} AS (`);
      lines.push(`  ${query}`);
      lines.push(`)`);
    } else if (!isLast) {
      lines.push(`, ${cteName} AS (`);
      lines.push(`  ${query}`);
      lines.push(`)`);
    } else {
      lines.push(`SELECT * FROM ${parentCte || cteName};`);
    }
  }

  return lines.join('\n');
}
